### PR TITLE
feat: add t.hasProp() and friends

### PR DESCRIPTION
**Pull request by isaacs**
Re: https://github.com/tapjs/node-tap/issues/763

### CODE REVIEW

**Comment by mandaputtra** [comment]
Wow ~ this is fast 🥇 Checked the test, and it is what I wanted. Just one question though

```
const p = { a: 'b', c: undefined, d: undefined }
const c = Object.assign(Object.create(p), { d: 'd', e: undefined, f: 'f' })
```

Why not writing it like this and get rid of the Object.assign() ? Since the variable `p` not used inside test.

```
const c = { a: 'b', c: undefined, d: 'd', e: undefined, f: 'f'  }
```

**Comment by isaacs** [comment]
> Why not writing it like this and get rid of the Object.assign() ?

Because the test is verifying the behavior of ownProperties vs inherited properties.

**Comment by isaacs** [comment]
Hmm, the plural versions should insist that `wanted` is an array, otherwise `t.hasProps({xy:1}, 'xy')` will fail because it looks for `'x'` and `'y'`, as strings are iterable.

**Comment by isaacs** [comment]
I guess it could check `wanted && typeof wanted === 'object'`, so any iterable object will work (like a Map.keys() collection or something).

**Comment by mandaputtra** [comment]
Strictly requiring the `wanted` is array on `t.hasProps` are better IMO.

**Comment by isaacs** [comment]
published in 15.2.0 https://node-tap.org/docs/api/asserts/#thaspropfound-property-message-extra

**Pull request merged**
